---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rate-ukma-postgres
  namespace: production
spec:
  encryptedData:
    password: AgB8sLd82oWpTKTv0tdeV8irB9nsvJeOI2dSknfFbTw9AdDTqSwnfYOmf+nfRoi7J31ODHnoM4za/1PYjmJtHtSFiDPBmvoK1GyGoVTKjgt/wcNFkJdXxSIpUdn1aDnzEo5HqTNPxG+imfLPqQdE2q0s1M4g1WGI34QF+rFB7jLiknF52r/xgOJNlBQtYNLhLFRaCZaSaQwacIGvgyOXOQbPgnFw1fPdypZKHaEvWZYdVmDStBQjqzYp6PVuf4LmaDM3ohlUo7JD8mKhtFGKv7VTL+4i8XOYqQIvoJyyOje59UbwjLgbmtOo0XlVUTNESWzG86JVpzIP98R4UOK5bC9PSJiYWTKu9SltB2o2bUF6Wi1SvVpEpfbFoV4qD9bvAZgul2cFm+7676RLbJfquF2BigGmlbFPprZwRZYwpu8AkIrMDlqsonoxOfWXsyl7O4xBnb2zW62fg46aNsxZMxVxcxLeDlJV2J0NBqBBihfTMExtZIAAFejZhRT/P24udcpcs7E/C4WAujCuyPMl6lCGQhnzgGulsvJJRqaCW2S10EPI9reFSoTk2H/YhJEWZVKgBk05TpWAISo0BYGUW/95uC2BPdU+UaephWL/xBhih9zTS+LXjjgBr2MqiAoPLUOA1BSqB1efh8ocYY9HmTZm0nN7UUqN6QknA6Ik3ZkgMh650vKwCFw7vJI+XCt81ZHBUOu8Bv3LXziajsBCkhGN
    username: AgBuckGFd4kZddK11+Bk3HIuBxSO9CX6HmQ0NXAvubhoLt467Acow2CoEWPw2lgSRVbevmnEU/4DwsIPeBfFFtezVIlsWtPfmuYBoUrBaMADXbchMqvR+28LzRkPZejT/7CR3bZEv9H8vU4cJhFFiFml4FSuYhpCBQsVoVtCBIyOk6cOVwX/9d3Y8epbCLhABlXW75JhLXf3/qe5MNWgo/fztr+TVT3OGnjHLixhMFKi9gq0VUY8Z055yf0LdSJCNwd2/FnAsgruuyhGxVJbr3hCI42WaPQiq102esD18Ek+zZQhBBtJIcA9URovBOOA7RvTn7qqKdUIvAJgTx45AqndkZEZPRIcnU21himFodSz2rIV8a5AQda3hxzpNQAYdMrBWGgIx2aMdwIVE7jaeJ3cgbVG+1/97jcPuJWGr9pPK6z0TePrFtcAuT1tRvwv0ldMnu+/JaZsOsEKXm92GMyd6qVX383ZW8lblFAaH30yjok/FWcmHB9/decUvTNN6QS31tiGNhbDmK9B2uGIxUyqIQa2y8g+hy6lWa6t6jxYYbH32BY01FjJIBb6diq4Lcdl4Mg5kfFFn/WvdXkVTLZScAs8LMGrojXsbtKxjFmNrcId25pUhvna/IR2xzQXqJJjLDYEYT2jvel+2zXXeoh4BckAjIXy3BtyJ/u+wy+I9Cuyh9hC+0EzKCrzJP118i5uO/dcdwAjow==
  template:
    metadata:
      name: rate-ukma-postgres
      namespace: production
    type: Opaque
