apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: rate-ukma-webapp-live
  namespace: flux-system
spec:
  image: ghcr.io/ukma-cs-ssdm-2025/rate-ukma/webapp
  interval: 1m0s
  secretRef:
    name: ghcr-auth
