nameOverride: ""
fullnameOverride: ""

# imagePullSecrets:
#   - name: ghcr-auth

environment: staging

backend:
  image:
    repository: ghcr.io/ukma-cs-ssdm-2025/rate-ukma/backend
    tag: "0.0.0" # {"$imagepolicy": "flux-system:rate-ukma-backend:tag"}
    pullPolicy: IfNotPresent
  replicaCount: 1
  gunicorn:
    workers: 2
    threads: 2
  resources: {}
  env:
    LOGIN_REDIRECT_URL: "http://app.staging.local/"
    LOGOUT_REDIRECT_URL: "http://app.staging.local/"
    LOGIN_ERROR_URL: "http://app.staging.local/auth/failed"

frontend:
  image:
    repository: ghcr.io/ukma-cs-ssdm-2025/rate-ukma/webapp
    tag: "staging-0.0.0" # {"$imagepolicy": "flux-system:rate-ukma-webapp-staging:tag"}
    pullPolicy: IfNotPresent
  replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  host: app.staging.local
  tls: false
  tlsSecretName: ""

postgres:
  instances: 1
  storage:
    size: 5Gi

redis:
  maxMemory: 256mb
  maxMemoryPolicy: allkeys-lfu
