apiVersion: v1
kind: Service
metadata:
  name: {{ include "rate-ukma.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rate-ukma.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
