apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rate-ukma
  namespace: production
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/rate-ukma
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  targetNamespace: production
  timeout: 15m
  install:
    createNamespace: true
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  values:
    environment: production
    imagePullSecrets:
      - name: ghcr-auth
    backend:
      image:
        tag: "v1.7.6" # {"$imagepolicy": "flux-system:rate-ukma-backend:tag"}
      replicaCount: 2
      gunicorn:
        workers: 4
        threads: 2
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      env:
        LOGIN_REDIRECT_URL: "https://k8s-beta.rateukma.com/"
        LOGOUT_REDIRECT_URL: "https://k8s-beta.rateukma.com/"
        LOGIN_ERROR_URL: "https://k8s-beta.rateukma.com/auth/failed"
    frontend:
      image:
        tag: "k8s-beta-v1.7.5" # {"$imagepolicy": "flux-system:rate-ukma-webapp-k8s-beta:tag"}
      replicaCount: 1
    ingress:
      enabled: true
      className: nginx
      host: k8s-beta.rateukma.com
      tls: true
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
    postgres:
      instances: 2
      storage:
        size: 10Gi
    redis:
      maxMemory: 512M
      maxMemoryPolicy: allkeys-lfu
